name: CI

on: [workflow_dispatch]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      # - name: Install and Build
      #   run: |
      #     npm install
      #     npm run lint
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and publish Docker image
        if: github.ref == 'refs/heads/main'
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: jfdidev/oidc-server
          username: jfdidev
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          platforms: linux/amd64,linux/arm64
